version: "3"
services:
  app:
    build: .
    image: pos-app
    container_name: pos-app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: pos-db
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d